rest:
  ssl: true
  host: repositorio.ufla.br
  port: 443
  nameSpace: /server

# Theme Config
themes:
  - name: ufla
    headTags:
    - tagName: link
      attributes:
        rel: icon
        href: assets/ufla/images/favicons/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: icon
        href: assets/ufla/images/favicons/favicon.svg
        type: image/svg+xml
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/ufla/images/favicons/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/ufla/images/favicons/manifest.webmanifest

defaultLanguage: pt-BR

info:
  enableEndUserAgreement: true
  enablePrivacyStatement: true
  enableCOARNotifySupport: false
